# Generated by Django 3.2.16 on 2024-09-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
        ('blog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdmin',
        ),
    ]
