# Generated by Django 3.2.16 on 2024-09-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_useradmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
